[package]
name = "fil_actor_account"
description = "Builtin account actor for Filecoin"
version = "6.0.0"
license = "MIT OR Apache-2.0"
authors = ["Filecoin Core Devs"]
edition = "2018"
keywords = ["filecoin", "web3", "wasm"]

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
actors-runtime = { path = "../runtime" }
fvm_shared = { git = "https://github.com/filecoin-project/ref-fvm", default-features = false }
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
num-derive = "0.3.0"

[dev-dependencies]
actors-runtime = { path = "../runtime", features = ["test_utils"] }

