[package]
name = "fil_actor_paych"
description = "Builtin paych actor for Filecoin"
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/filecoin-project/canonical-actors"

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
actors-runtime = { path = "../runtime" }
fvm_shared = { git = "https://github.com/filecoin-project/ref-fvm", default-features = false }
num-traits = "0.2"
num-derive = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }
anyhow = "1.0.51"

[dev-dependencies]
actors-runtime = { path = "../runtime", features = ["test_utils"] }
ipld_amt = { git = "https://github.com/filecoin-project/ref-fvm", features = ["go-interop"]}
derive_builder = "0.10"
