[package]
name = "fvm_actor_market"
description = "Builtin market actor for Filecoin"
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/filecoin-project/canonical-actors"

[lib]
crate-type = ["cdylib"]

[dependencies]
actors-runtime = { path = "../runtime" }
fvm_shared = { path = "../../../fvm/shared", default-features = false }
num-traits = "0.2"
num-derive = "0.3.0"
bitfield = { package = "ipld_bitfield", path = "../../../fvm/ipld/bitfield" }
ahash = "0.7"
serde = { version = "1.0", features = ["derive"] }
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }
log = "0.4.8"
anyhow = "1.0.51"

[dev-dependencies]
actors-runtime = { path = "../runtime", features = ["test_utils"] }
ipld_amt = { path = "../../../fvm/ipld/amt", features = ["go-interop"]}
