[package]
name = "actors-runtime"
description = "System actors for the Filecoin protocol"
version = "4.0.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
ipld_hamt = { git = "https://github.com/filecoin-project/ref-fvm", branch = "raulk/extract-actors" }
ipld_amt = { git = "https://github.com/filecoin-project/ref-fvm", branch = "raulk/extract-actors", features = ["go-interop"]}
fvm_shared = { git = "https://github.com/filecoin-project/ref-fvm", branch = "raulk/extract-actors", default-features = false }
num-traits = "0.2"
num-derive = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
unsigned-varint = "0.7.1"
integer-encoding = { version = "3.0", default-features = false }
byteorder = "1.3.4"
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }
multihash = { version = "0.16.1", default-features = false, features = ["identity"] }
base64 = "0.13"
log = "0.4.8"
indexmap = { version = "1.7.0", features = ["serde-1"] }
thiserror = "1.0.30"
# enforce wasm compat
getrandom = { version = "0.2", features = ["js"] }
hex = { version = "0.4.2", optional = true }
anyhow = "1.0.51"

[target.'cfg(target_arch = "wasm32")'.dependencies]
fvm_sdk = { git = "https://github.com/filecoin-project/ref-fvm", branch = "raulk/extract-actors" }

[dev-dependencies]
derive_builder = "0.10"
hex = "0.4.2"

[features]
default = []
devnet = []
interopnet = []
test_utils = ["hex"]
