[package]
name = "fil_actor_multisig"
description = "Builtin multisig actor for Filecoin"
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/filecoin-project/canonical-actors"

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
actors-runtime = { path = "../runtime" }
fvm_shared = { git = "https://github.com/filecoin-project/ref-fvm", branch = "raulk/extract-actors", default-features = false }
ipld_hamt = { git = "https://github.com/filecoin-project/ref-fvm", branch = "raulk/extract-actors" }
num-traits = "0.2"
num-derive = "0.3.0"
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }
indexmap = { version = "1.7.0", features = ["serde-1"] }
integer-encoding = { version = "3.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.51"
