[package]
name = "fil_actor_market"
description = "Builtin market actor for Filecoin"
version = "6.0.0"
license = "MIT OR Apache-2.0"
authors = ["Filecoin Core Devs"]
edition = "2018"
repository = "https://github.com/filecoin-project/builtin-actors"
keywords = ["filecoin", "web3", "wasm"]

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
actors-runtime = { path = "../runtime" }
fvm_shared = { git = "https://github.com/filecoin-project/ref-fvm", default-features = false }
bitfield = { package = "ipld_bitfield", git = "https://github.com/filecoin-project/ref-fvm" }
num-traits = "0.2"
num-derive = "0.3.0"
ahash = "0.7"
serde = { version = "1.0", features = ["derive"] }
cid = { version = "0.8.2", default-features = false, features = ["serde-codec"] }
log = "0.4.8"
anyhow = "1.0.51"

[dev-dependencies]
actors-runtime = { path = "../runtime", features = ["test_utils"] }
ipld_amt = { git = "https://github.com/filecoin-project/ref-fvm", features = ["go-interop"]}
