name: Continuous integration

on:
  push:
    branches:
      - master
      - next
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Running rustfmt
      uses: ./.github/actions/rust-cargo-run
      with:
        command: fmt
        args: -- --check
        components: rustfmt
        github_token: ${{ secrets.GITHUB_TOKEN }}

  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Running clippy
      run: make check

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Running tests
      uses: ./.github/actions/rust-cargo-run
      with:
        command: test
        args: --locked --all --no-fail-fast
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      CACHE_SKIP_SAVE: ${{ matrix.push == '' || matrix.push == 'false' }}
    strategy:
      matrix:
        network: [ 'mainnet', 'caterpillarnet', 'butterflynet', 'calibrationnet', 'devnet', 'testing', 'testing-fake-proofs', 'wallaby', 'devnet-wasm' ]
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: ./.github/actions/rust-cargo-run
      with:
        command: version
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Writing bundle
      env:
        BUILD_FIL_NETWORK: ${{ matrix.network }}
      run: |
        cargo run --locked -- -o output/builtin-actors.car
    - name: Checking no wasm-bindgen references
      run: |
        sudo apt-get update && sudo apt-get -y install wabt parallel
        find ./target -name '*.wasm' -print0 | parallel -0 --halt now,fail=1 sh -c 'wasm2wat --enable-bulk-memory {} | grep bindgen; test $? -ne 0'
