name: Continuous integration

on:
  push:

jobs:
  test:
    runs-on: ${{ fromJSON(github.repository == 'filecoin-project/builtin-actors' && '["self-hosted", "linux", "x64", "4xlarge"]' || '"ubuntu-latest"') }}
    steps:
    - name: Checking out
      uses: actions/checkout@v3
    
